"""add kd,hs,adr and peak_rank

Revision ID: 03811923a101
Revises: c26ab8699a98
Create Date: 2025-08-12 08:51:10.275536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '03811923a101'
down_revision: Union[str, None] = 'c26ab8699a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activematchplayer', sa.Column('kd', sa.Float(), nullable=True))
    op.add_column('activematchplayer', sa.Column('hs', sa.Integer(), nullable=True))
    op.add_column('activematchplayer', sa.Column('adr', sa.Integer(), nullable=True))
    op.add_column('activematchplayer', sa.Column('peak_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activematchplayer', 'peak_rank')
    op.drop_column('activematchplayer', 'adr')
    op.drop_column('activematchplayer', 'hs')
    op.drop_column('activematchplayer', 'kd')
    # ### end Alembic commands ###
