"""empty message

Revision ID: 9917caeaf089
Revises: 
Create Date: 2025-07-22 15:59:46.418587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9917caeaf089'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activematch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('match_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('game_map', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('game_start', sa.DateTime(), nullable=True),
    sa.Column('game_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('party_owner_score', sa.Integer(), nullable=True),
    sa.Column('party_owner_enemy_score', sa.Integer(), nullable=True),
    sa.Column('party_owner_average_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('party_owner_enemy_average_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activematch_match_uuid'), 'activematch', ['match_uuid'], unique=True)
    op.create_table('activematchplayer',
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('character', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('game_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_level', sa.Integer(), nullable=True),
    sa.Column('player_card_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('player_title_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_level_border_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rank', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rr', sa.Integer(), nullable=True),
    sa.Column('leaderboard_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['activematch.id'], ),
    sa.PrimaryKeyConstraint('subject', 'match_id')
    )
    op.create_index(op.f('ix_activematchplayer_match_id'), 'activematchplayer', ['match_id'], unique=False)
    op.create_index(op.f('ix_activematchplayer_subject'), 'activematchplayer', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activematchplayer_subject'), table_name='activematchplayer')
    op.drop_index(op.f('ix_activematchplayer_match_id'), table_name='activematchplayer')
    op.drop_table('activematchplayer')
    op.drop_index(op.f('ix_activematch_match_uuid'), table_name='activematch')
    op.drop_table('activematch')
    # ### end Alembic commands ###
