"""adapt

Revision ID: b2fc813e50c0
Revises: 839f36676feb
Create Date: 2025-05-23 15:48:27.048265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2fc813e50c0'
down_revision: Union[str, None] = '839f36676feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matchplayer', 'kills',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matchplayer', 'deaths',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matchplayer', 'assists',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matchplayer', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matchplayer', 'agent',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'tag',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'tag',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('matchplayer', 'agent',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('matchplayer', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matchplayer', 'assists',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matchplayer', 'deaths',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matchplayer', 'kills',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
