"""add party owner teamid

Revision ID: c26ab8699a98
Revises: 9917caeaf089
Create Date: 2025-07-22 16:08:40.665318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c26ab8699a98'
down_revision: Union[str, None] = '9917caeaf089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activematch', sa.Column('party_owner_team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activematch', 'party_owner_team_id')
    # ### end Alembic commands ###
